workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini
    environment:
      vars:
        XCODE_WORKSPACE: "App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.example.app"
        XCODE_PROJECT: "App/App.xcodeproj"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install pods
        script: |
          cd App
          pod install
      - name: Build
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - your.email@example.com
